import React from 'react';
import './PrivacyPolicy.css';

const PrivacyPolicy = ({ onAccept }) => {
    return (
      <div className="legal-document-container">
        <div className="legal-content">
          <h1>Privacy Policy</h1>
          <p className="last-updated">Last updated on 23/9/2024</p>
        
        <h2>1. INTRODUCTION</h2>
        <p>Welcome to the AI Chatterbox platform, developed by SWISP Lab. We are committed to protecting your privacy and ensuring your personal data is handled in a secure and responsible manner. This Privacy Policy outlines how we collect, use, and safeguard your information when you use our services.</p>
        
        <h2>2. DATA WE COLLECT</h2>
        <p>We collect the following data from users interacting with the AI Chatterbox:</p>
        <ul>
          <li>User Input: Text inputs provided by users when interacting with the AI to generate speculative questions.</li>
          <li>Generated Questions and Responses: Data about the questions generated by the system based on user input.</li>
          <li>Demographic Information: Optional data such as age, location, and preferred language for research purposes.</li>
          <li>Usage Data: Data about how users interact with the platform (e.g., time spent, frequency of interaction, etc.).</li>
        </ul>

        <h2>3. HOW WE USE YOUR DATA</h2>
        <p>We use the collected data to:</p>
        <ul>
          <li>Improve User Experience: Enhance the platform's performance and tailor questions based on user input.</li>
          <li>Research and Development: Analyze user interactions to improve AI algorithms and research user engagement with speculative thinking exercises.</li>
          <li>Compliance and Security: Protect the platform from unauthorized use and ensure data privacy and security.</li>
        </ul>

        <h2>4. DATA SECURITY</h2>
        <p>We prioritize the protection of your personal data. The platform uses industry-standard encryption techniques, such as:</p>
        <ul>
          <li>TLS (Transport Layer Security) for secure data transmission.</li>
          <li>AES-256 encryption for protecting stored data, including user input and interaction history.</li>
          <li>MongoDB Queryable Encryption to safeguard sensitive data in our database.</li>
        </ul>
        <p>Regular security audits and penetration testing are performed to ensure data security and to protect against vulnerabilities.</p>

        <h2>5. DATA RETENTION</h2>
        <p>We retain your data for as long as necessary to fulfill the purposes outlined in this Privacy Policy:</p>
        <ul>
          <li>Interaction Data: Stored securely for research and improvement of the platform.</li>
          <li>Personal Information: Retained only as long as required for research purposes or as mandated by law.</li>
        </ul>
        <p>If you wish to delete your data, please contact us at sarah.healy@unimelb.edu.au.</p>

        <h2>6. YOUR RIGHTS</h2>
        <p>As a user, you have the following rights regarding your data:</p>
        <ul>
          <li>Access: Request access to the data we hold about you.</li>
          <li>Correction: Correct any inaccurate or incomplete information.</li>
          <li>Deletion: Request the deletion of your personal data.</li>
          <li>Data Portability: Request a copy of your data in a structured format.</li>
        </ul>
        <p>To exercise any of these rights, contact us at sarah.healy@unimelb.edu.au.</p>

        <h2>7. COOKIES AND TRACKING</h2>
        <p>We may use cookies to enhance user experience and track usage for analytical purposes. You can manage or disable cookies in your browser settings. We also use Google reCAPTCHA to protect against automated bots.</p>

        <h2>8. SHARING OF DATA</h2>
        <p>We do not share or sell your personal data to third parties. However, anonymized data may be shared for research and analysis purposes.</p>

        <h2>9. CHANGES TO THIS PRIVACY POLICY</h2>
        <p>We may update this Privacy Policy from time to time. Any changes will be communicated on this page with the updated effective date.</p>

        <h2>10. CONTACT US</h2>
        <p>For questions or concerns about this Privacy Policy or your data, please reach out to us at sarah.healy@unimelb.edu.au.</p>
      </div>
      
      <button className="accept-button" onClick={onAccept}>
      Back
      </button>
    </div>
  );
};

export default PrivacyPolicy;